service: sc5-serverless-boilerplate # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:*
      Resource: arn:aws:dynamodb:${self:provider.region}:*:*
    - Effect: Allow
      Action:
      - SNS:*
      Resource: arn:aws:sns:${self:provider.region}:*:*
package:
  exclude:
    - test/**
    - .git/**

functions:
  hello: 
    handler: fnHello/handler.hello
    events:
      - http:
          path: hello
          method: get
          integration: lambda

plugins:
  - serverless-mocha-plugin
  - serverless-webpack
  - serverless-offline

resources:
  Resources: ${file(./resources/resources.yml)}